### PR TITLE
Fixes #1:  Add newCodeplug action

### LINKED ISSUE #1: Add newCodeplug action to dmrRadio to create new empty rdt
This is a new feature request.

It would be very useful to be able to automate the generation of brand new empty codeplug rdt files using the dmrRadio command-line tool.  Perhaps something like ```dmrRadio newCodeplug -model <model> -freq <freqRange> <codeplugFile>```.

My use-case for this new feature would be to create a new empty codeplug suitable for passing on to dmrRadio's "codeplugToJSON" action to obtain a JSON file which may then be further modified using jq and Python.

I have created a quick-and-dirty Python script to import CHIRP CSV files and spit them out as channels as an alternative to manual data entry (https://github.com/tylert/freq-lists/blob/master/codeplugs/chirp_channels.py).  I use this to build up new, modularized codeplugs for specific users/tasks.

### PR DESCRIPTION
**Pull request by tylert**
@DaleFarnsworth

### CODE REVIEW

**Comment by DaleFarnsworth** [comment]
Looks good at first glance.  Thanks!  I'll add it today.

**Comment by tylert** [comment]
Only thing it doesn't do yet is to error if the file already exists.

**Comment by DaleFarnsworth** [comment]
It silently overwrites any existing file.  I consider this desirable behavior.  Just like most UNIX commands.
I commited your change with a very slight change.  Thanks!

**Comment by tylert** [comment]
FB!  Agreed, it is the Unix way to weed out those who have weak directory management skills :)  Thanks again.

**Pull request closed without merging**
